graph LR
LPWAN --> GSM
GSM -- GSM Discontinued--> EC-GSM
LPWAN --> UNB
UNB --> SigFox
UNB --> NB-Fi
LPWAN --> LoRa
LPWAN --> Localization
LPWAN --> Satellite
LPWAN --> Comparisons/survey
LPWAN --> LTE
LTE --> Cat-M
LTE --> NB-IoT
M2M-system --> NB-IoT
SDR --> NB-IoT
NB-IoT --> Group-comms
NB-IoT --> Evaluation/analysis/overview/simulation
Fields --> Medical
Fields --> Industrial
Fields --> Smart-Cities
Smart-Grid/Cities --> Vehicle/Parking
Applications --> Vehicle/Parking
Performance --> Energy-efficiency
Performance --> RF
RF --> Co-existence
RF --> Band
Performance --> Throughput
Performance --> Coverage
Performance --> Capacity
Performance --> Deployment
Performance --> Power
Optimization --> Data
Optimization --> Battery
Present -- 3GPP --> Rel13
Future -- 3GPP --> Rel14
Rel14 --> Rel15
Rel15 --> 5G
Rel14 --> Mobility
Mobility --> Inter-cell-reselection


